### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by ncherukukota-mdsol** [arduino/setup-task#680]
### Describe the problem

Hi,
Run arduino/setup-task@v1
  with:
    version: [3]
certificate has expired
Waiting 16 seconds before trying again

### To reproduce

    - name: Install Task
      id: task
      uses: arduino/setup-task@v1
      with:
        version: 3.15.0

### Expected behavior

Task gets installed on the runner

### 'arduino/setup-task' version

v1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/setup-task/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @ncherukukota-mdsol. Thanks for your report. Does the problem still occur if you try again now?

This type of problem might be caused by a transient network outage. These usually resolve themselves after a matter of minutes; hours at worst. If so in this case, I would expect you would no longer experience the problem now.

**Comment by per1234** [comment]
Closing due to lack of response.

@ncherukukota-mdsol if you will provide the requested information by commenting here, I'll be happy to re-open this issue.
